<Project>
  <Import Project="$(MSBuildThisFileDirectory)release\PackageVersions.props"
          Condition="Exists('$(MSBuildThisFileDirectory)release\PackageVersions.props')" />
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <_OrchestratorEmitWorkflowActionCatalogDefaultedFalse Condition="'$(OrchestratorEmitWorkflowActionCatalog)' == ''">true</_OrchestratorEmitWorkflowActionCatalogDefaultedFalse>
    <OrchestratorEmitWorkflowActionCatalog Condition="'$(OrchestratorEmitWorkflowActionCatalog)' == ''">false</OrchestratorEmitWorkflowActionCatalog>
    <GeneratePackageOnBuild Condition="'$(GeneratePackageOnBuild)' == ''">false</GeneratePackageOnBuild>
  </PropertyGroup>
  <PropertyGroup>
    <Authors Condition="'$(Authors)' == ''">Reimaginate</Authors>
    <Copyright Condition="'$(Copyright)' == ''">Copyright Reimaginate Pty Ltd</Copyright>
    <PackageProjectUrl Condition="'$(PackageProjectUrl)' == ''">https://github.com/Reimaginate/Orchestrator</PackageProjectUrl>
    <RepositoryUrl Condition="'$(RepositoryUrl)' == ''">https://github.com/Reimaginate/Orchestrator</RepositoryUrl>
    <PackageLicenseExpression Condition="'$(PackageLicenseExpression)' == ''">MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance Condition="'$(PackageRequireLicenseAcceptance)' == ''">True</PackageRequireLicenseAcceptance>
    <PackageReadmeFile Condition="'$(PackageReadmeFile)' == '' and Exists('$(MSBuildProjectDirectory)\README.md')">README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup Condition="Exists('$(MSBuildProjectDirectory)\README.md')">
    <None Include="$(MSBuildProjectDirectory)\README.md" Pack="true" PackagePath="\" Link="README.md" />
  </ItemGroup>
  <PropertyGroup Condition="'$(GeneratePackageOnBuild)' == 'True'">
    <DebugType>portable</DebugType>
    <Deterministic>true</Deterministic>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
</Project>
